spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(cuLOhHRtVIguaunfYi2h6VVxgCbF1bt6c1ZZluglf5p4Op2TyL4xFMfWB4wusDjL5blT6JHUyAUBLXRF2JzKuOBPoeJW64tg)
    username: ENC(VONpVwD4Rb/FO1n/sehxpFVNIDT8xCU0)
    password: ENC(VONpVwD4Rb/FO1n/sehxpFVNIDT8xCU0)
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 30
      maxLifeTime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        #hbm2ddl.auto: create-only
    show-sql: true
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: taxiapp
    key-store-type: PKCS12
    key-alias: taxiapp
  http2:
    enabled: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
jwt:
  prefix: token
  header: Authorization
  secretKey: ENC(HbToPk+jpbyhLBSGCjjCzg==)
  expireTime: 864000000 #millisecond